Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HirePros.Models
{
    public class User
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public IList<UserProf> UserProf { get; set; } = new List<UserProf>();
        //to store the relationship between Users shortlisting various professionals

        public User()
        {

        }
    }
}

ViewModels/ViewUserProfViewModel.cs
using HirePros.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HirePros.ViewModels

{
    public class ViewUserProfViewModel
    {
        public User User { get; set; }
        public IList<UserProf> Listing { get; set; }

    }
}

Controllers/ProfessionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HirePros.Data;
using HirePros.Models;
using HirePros.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HirePros.Controllers
{
    public class ProfessionalController : Controller
    {
        private readonly ServiceDbContext context;// private so only accessed by this class ; this is a way to reference the objects
        //refernce used to interface with the database
        public ProfessionalController(ServiceDbContext dbContext)//overload to reference the private field context
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("UserName") == "Admin")
            {
                IList<Professional> professionals = context.Professionals.Include(p => p.Services).ToList();
                //accessed by context as Professionals ia a dbset that holds on to Professional class objects and turn that dbset into a list


                return View(professionals);
            }

            return Redirect("User/Index?username="+ HttpContext.Session.GetString("UserName"));
            //return Redirect("Home");
            
        }

        public IActionResult Add()
        {
            //Viemodel will take the list of categories and create a select list with the below
            if (HttpContext.Session.GetString("UserName") == "Admin")
            {
                AddProfessionalViewModel addProfessionalViewModel = new AddProfessionalViewModel(context.Services.ToList());
                ViewBag.Title = "Professionals";
                return View(addProfessionalViewModel);
            }
            return Redirect("/User/Index?username=" + HttpContext.Session.GetString("UserName"));
        }

        [HttpPost]
        public IActionResult Add(AddProfessionalViewModel addProfessionalViewModels)
        {
            if (ModelState.IsValid)
            {
                Services newService = context.Services.Single(s => s.ID == addProfessionalViewModels.ServicesID);

                Professional newProf = new Professional
                {

                    Name = addProfessionalViewModels.Name,
                    Description = addProfessionalViewModels.Description,
                    Email = addProfessionalViewModels.Email,
                    Services = newService
                };

                context.Professionals.Add(newProf);
                context.SaveChanges();

                return Redirect("/Professional");
            }

            return View(addProfessionalViewModels);
        }


        //to list all professionals catering to a particular service
        public IActionResult Service(int id)
        {
            if (id == 0)//If id is not specified
            {
                return Redirect("/Home");

            }


            Services theServ = context.Services.Include(prof => prof.Professionals).Single(prof => prof.ID == id);
            //to refernce all the professionals from the other side of the relationship, services side

            ViewBag.Title = "Professionals provinding " + theServ.ServiceName + " :";

            return View("Index", theServ.Professionals);


        }
    }
}

Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HirePros.Data;
using HirePros.Models;
using HirePros.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HirePros.Controllers
{
    public class ServiceController : Controller
    {
        private readonly ServiceDbContext context;

        public ServiceController(ServiceDbContext dbContext)
        {
            context = dbContext;
        }

        //Get Controller
        public IActionResult Index()
        {
            
            List<Services> servs = context.Services.ToList();
            return View(servs);
            
            //return Redirect("User/Index?username=" + HttpContext.Session.GetString("UserName"));
        }

        //Get Controller
        public IActionResult Add()
        {
            if (HttpContext.Session.GetString("UserName") == "Admin")
            {
                AddServiceViewModel addServiceViewModel = new AddServiceViewModel();
                return View(addServiceViewModel);
            }
            return Redirect("/User/Index?username=" + HttpContext.Session.GetString("UserName"));


        }

        //Post Controller

        [HttpPost]
        public IActionResult Add(AddServiceViewModel addServiceViewModel)
        {
            if (ModelState.IsValid)
            {
                Services newService = new Services
                {
                    ServiceName = addServiceViewModel.ServiceName,
                    ServiceDesc = addServiceViewModel.ServiceDesc
                };

                context.Services.Add(newService);
                context.SaveChanges();

                return Redirect("/Service");
            }

            return View(addServiceViewModel);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HirePros.Data;
using HirePros.Models;
using HirePros.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
//using System.Web.MVC;

namespace HirePros.Controllers
{
    public class UserController : Controller
    {
        private readonly ServiceDbContext context;
        public UserController(ServiceDbContext dbContext)
        {
            context = dbContext;
        }


        public IActionResult Index(string Username = "User")// if there is no username it says welcome User
        {
            ViewBag.Username = Username;
            User user = context.Users.Single(u => u.Username == Username);
            return View(user);
        }

        public IActionResult Add()
        {
            AddUserViewModel addUserViewModel = new AddUserViewModel();
            return View(addUserViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddUserViewModel addUserViewModel)
        {
            if (ModelState.IsValid)
            {
                User newUser = new User
                {
                    Username = addUserViewModel.Username,
                    Email = addUserViewModel.Email,
                    Password = addUserViewModel.Password
                };
                

                context.Users.Add(newUser);
                context.SaveChanges();

                return Redirect("Index?username=" + newUser.Username);
                //return Redirect("VieUserProf/"+newUser.ID);

            }

            return View(addUserViewModel);
        }

        public IActionResult Login()
        {
            AddUserViewModel addUserViewModel = new AddUserViewModel();
            return View(addUserViewModel);
        } 

        [HttpPost]
        public IActionResult Login(AddUserViewModel addUserViewModel)
        {
            User newUser = context.Users.Single(u => u.Username == addUserViewModel.Username);
            if (newUser!=null)
            {
               
                //HttpContext.Session session= new HttpContext.Session() { newUser.Username };
                HttpContext.Session.SetString("UserName", newUser.Username);
                if(newUser.Username=="Admin")
                {
                    return Redirect("Index?username="+newUser.Username);
                }
                return Redirect("ViewUserProf/" + newUser.ID);
            }
            
            return View(addUserViewModel);
        }

        public IActionResult ViewUserProf(int id)
        {
            User newUser = context.Users.Single(u => u.ID == id);
            List<UserProf> listing = context.UserProfs.Include(listing => listing.Professional).Where(up => up.UserID == id).ToList();

            ViewUserProfViewModel viewUserProfViewModel = new ViewUserProfViewModel
            {
                User = newUser,
                Listing = listing
            };

            return View(viewUserProfViewModel);
        }

        //Menu/AddPros/3
        public IActionResult AddUserPros(int id)
        {
            User user = context.Users.Single(u => u.ID == id);
            List<Professional> profs = context.Professionals.ToList();
            AddUserProfViewModel addUserProfViewModel = new AddUserProfViewModel(user, profs);
            return View(addUserProfViewModel);
        }

        [HttpPost]
        public IActionResult AddUserPros(AddUserProfViewModel addUserProfViewModel)
        {
            if (ModelState.IsValid)
            {
                var professionalID = addUserProfViewModel.ProfessionalID;
                var userID = addUserProfViewModel.UserID;

                IList<UserProf> existingPro = context.UserProfs.Where(up => up.UserID == userID).Where(p => p.ProfessionalID == professionalID).ToList();

                if (existingPro.Count == 0)
                {
                    UserProf userList = new UserProf
                    {
                        ProfessionalID = professionalID,
                        UserID = userID

                    };
                    context.UserProfs.Add(userList);
                    context.SaveChanges();
                    return Redirect("/User/ViewUserProf/" + addUserProfViewModel.UserID);
                }


            }

            return View(addUserProfViewModel);
        }


    }
}

Views/User/Add.cshtml
@model HirePros.ViewModels.AddUserViewModel


<h1>User Signup </h1>
<form method="post">

    <div class="form-group">
        <label asp-for="@Model.Username"></label><br />
        <input class="form-control" asp-for="@Model.Username" value="@Model.Username" />
        <span asp-validation-for="@Model.Username"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Email"></label><br />
        <input class="form-control" asp-for="@Model.Email" value="@Model.Email" />
        <span asp-validation-for="@Model.Email"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Password"></label><br />
        <input class="form-control" asp-for="@Model.Password" />
        <span asp-validation-for="@Model.Password"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Verify"></label><br />
        <input class="form-control" asp-for="@Model.Verify" />
        <span asp-validation-for="@Model.Verify"></span>
    </div>

    <input type="submit" value="SignUp" />
</form>

Views/User/AddUserPros.cshtml
@model HirePros.ViewModels.AddUserProfViewModel

<form asp-controller="User" asp-action="AddUserPros" method="post">
    <div class="form-group">
        <label asp-for="ProfessionalID"> </label>
        <select asp-for="ProfessionalID" asp-items="Model.Professionals"> </select>
        <span asp-validation-for="ProfessionalID"></span>

    </div>

    <input type="hidden" name="UserID" value="@Model.User.ID">


    <input type="submit" value="Shortlist Professional" />

</form>

Views/User/Index.cshtml
@model HirePros.Models.User

<h1>Welcome @ViewBag.Username</h1>

@if (Model.Username.Equals("Admin"))
{
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Professional" asp-action="Index">Professional</a>
    </li>
    <li><a asp-controller="Professional" asp-action="Add">Add Professional</a></li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="Index">Service</a>
    </li>
    <li><p><a asp-controller="Service" asp-action="Add">Add Services</a></p> </li>
</ul>
 }
else
{

    <p><a asp-controller="User" asp-action="AddUserPros" asp-route-id="@Model.ID">Add new professional to list</a></p>

    <p><a asp-controller="User" asp-action="ViewUserProf" asp-route-id="@Model.ID">Your list</a></p>


}

Views/User/Login.cshtml
@model HirePros.ViewModels.AddUserViewModel

@{
    ViewData["Title"] = "Login";
}
    <body>
        <h1>Login</h1>
        <form asp-controller="User" asp-action="Login" method="post">

            <div class="form-group">
                <label asp-for="@Model.Username"></label><br />
                <input class="form-control" asp-for="@Model.Username" value="@Model.Username" />
                <span asp-validation-for="@Model.Username"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Password"></label><br />
                <input class="form-control" asp-for="@Model.Password" />
                <span asp-validation-for="@Model.Password"></span>
            </div>

            <input type="submit" value="Login" />
        </form>
    </body>

Views/User/ViewUserProf.cshtml
@model HirePros.ViewModels.ViewUserProfViewModel

<h1>Welcome @Model.User.Username , your shortlisted professionals:</h1>


<ul>
    @foreach (var userProf in Model.Listing)
    {
        <li>@userProf.Professional.Name</li>
    }
</ul>

@if (Model.Listing.Count == 0)
{
    <p><i>No professionals selected yet</i></p>
}
else
{
    <p><a asp-controller="Service" asp-action="Index">Looking for</a></p>
    <br />

    <p><a asp-controller="User" asp-action="AddUserPros" asp-route-id="@Model.User.ID">Looking for Pros to Hire</a></p>
}